steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$COMMIT_SHA',
        '.',
      ]
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$COMMIT_SHA',
      ]
  # Deploy the container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--service-account'
      - 'spotify-web-api-demo-run@${PROJECT_ID}.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'BASE_URL=${_BASE_URL},SPOTIFY_CLIENT_ID=${_SPOTIFY_CLIENT_ID},LYRICS_MOOD_PROVIDER=openai'
      - '--set-secrets'
      - 'SPOTIFY_CLIENT_SECRET=${_SPOTIFY_CLIENT_SECRET_SECRET},LASTFM_API_KEY=${_LASTFM_API_KEY_SECRET},LASTFM_API_SECRET=${_LASTFM_API_SECRET_SECRET},OPENAI_API_KEY=${_OPENAI_API_KEY_SECRET}'
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE_NAME}:$COMMIT_SHA'
substitutions:
  _REGION: 'us-central1'
  _AR_REPO: 'spotify-web-api-demo'
  _SERVICE_NAME: 'spotify-web-api-demo'
  _BASE_URL: 'https://spotify-web-api-demo-1040938023586.us-central1.run.app'
  _SPOTIFY_CLIENT_ID: '1aa49071301549ad869e22dfb5e4982c'
  _SPOTIFY_CLIENT_SECRET_SECRET: 'SPOTIFY_CLIENT_SECRET:latest'
  _LASTFM_API_KEY_SECRET: 'LASTFM_API_KEY:latest'
  _LASTFM_API_SECRET_SECRET: 'LASTFM_API_SECRET:latest'
  _OPENAI_API_KEY_SECRET: 'OPENAI_API_KEY:latest'
options:
  logging: CLOUD_LOGGING_ONLY
