server.port=${PORT:8080}
server.forward-headers-strategy=native
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=8s
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=true
logging.level.root=INFO
logging.level.com.lis.spotify=INFO
logging.level.org.apache.coyote.http11.Http11Processor=WARN
server.tomcat.keep-alive-timeout=10s
server.tomcat.max-keep-alive-requests=100
